apiVersion: core/v1alpha1
kind: Job
metadata:
  name: window-aggregation-0.1
  project: demo
spec:
  artifactRef:
    jarOptions: {}
    name: window-aggregation-0.1
  flinkVersion: "1.16"
  resources:
    rpus: 2
zone: shared-aws-us-east-1

